Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/leena/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/leena/Library/Python/3.9/lib/python/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/leena/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "/Users/leena/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/leena/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from openmdao.utils.assert_utils import assert_near_equal
assert_near_equal(const, -1.68550507e-10, 1e-3)
assert_near_equal(const_K, 273.15, 1e-3)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[5], line 2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mopenmdao[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m[38;5;21;01m.[39;00m[38;5;21;01massert_utils[39;00m [38;5;28;01mimport[39;00m assert_near_equal
[0;32m----> 2[0m [43massert_near_equal[49m[43m([49m[43mconst[49m[43m,[49m[43m [49m[38;5;241;43m-[39;49m[38;5;241;43m1.68550507e-10[39;49m[43m,[49m[43m [49m[38;5;241;43m1e-3[39;49m[43m)[49m
[1;32m      3[0m assert_near_equal(const_K, [38;5;241m273.15[39m, [38;5;241m1e-3[39m)

File [0;32m~/dev/eecs481/hw6/OpenMDAO/openmdao/utils/assert_utils.py:574[0m, in [0;36massert_near_equal[0;34m(actual, desired, tolerance)[0m
[1;32m    572[0m [38;5;28;01mif[39;00m [38;5;28mabs[39m(error) [38;5;241m>[39m tolerance:
[1;32m    573[0m     [38;5;28;01mif[39;00m actual[38;5;241m.[39msize [38;5;241m<[39m [38;5;241m10[39m [38;5;129;01mand[39;00m desired[38;5;241m.[39msize [38;5;241m<[39m [38;5;241m10[39m:
[0;32m--> 574[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m'[39m[38;5;124mactual [39m[38;5;132;01m%s[39;00m[38;5;124m, desired [39m[38;5;132;01m%s[39;00m[38;5;124m, rel error [39m[38;5;132;01m%s[39;00m[38;5;124m, tolerance [39m[38;5;132;01m%s[39;00m[38;5;124m'[39m
[1;32m    575[0m                          [38;5;241m%[39m (actual, desired, error, tolerance))
[1;32m    576[0m     [38;5;28;01melse[39;00m:
[1;32m    577[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m'[39m[38;5;124marrays do not match, rel error [39m[38;5;132;01m%.3e[39;00m[38;5;124m > tol ([39m[38;5;132;01m%.3e[39;00m[38;5;124m)[39m[38;5;124m'[39m [38;5;241m%[39m
[1;32m    578[0m                          (error, tolerance))

[0;31mValueError[0m: actual [-1.66901604e-10], desired [-1.68550507e-10], rel error 0.009782844208595636, tolerance 0.001
ValueError: actual [-1.66901604e-10], desired [-1.68550507e-10], rel error 0.009782844208595636, tolerance 0.001

